name: 'Configuration Read-only'
type: module
description: 'Enables making the active configuration store read-only to prevent configuration changes on a Drupal site.'
package: Configuration
core_version_requirement: ^8.7.12 || ^9

# Information added by Drupal.org packaging script on 2020-08-05
version: '8.x-1.0-beta4'
project: 'config_readonly'
datestamp: 1596658249
